<script setup lang="ts">
const { request } = useAppApi();
const loading = ref(false); const source = ref('demo'); const rows = ref([{ rank: 1, name: 'Mai Anh', xp: 1280 }, { rank: 2, name: 'Quốc Huy', xp: 1130 }, { rank: 3, name: 'Bạn', xp: 5 }, { rank: 4, name: 'Linh Chi', xp: 860 }]);
onMounted(async () => { loading.value = true; try { const remote = await request<Array<{ rank: number; userId: string; xp: number }>>('/leaderboard/xp', { query: { limit: 10 } }); if (remote.length) { rows.value = remote.map((row) => ({ ...row, name: row.userId.slice(0, 8) })); source.value = 'live'; } } catch { /* Demo data keeps the page useful offline. */ } finally { loading.value = false; } });
</script>

<template>
  <div class="page-enter space-y-6"><section class="rounded-[26px] bg-[#FFF6DF] p-6 shadow-soft sm:p-9"><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-extrabold tracking-[0.18em] text-[#A87400]">LEADERBOARD</p><h1 class="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Tiến bộ có bạn đồng hành.</h1><p class="mt-3 max-w-xl text-sm leading-6 text-ink/60">XP là tín hiệu vui để giữ nhịp, không phải một cuộc đua phải thắng mỗi ngày.</p></div><span class="rounded-xl bg-white/70 px-3 py-2 text-xs font-bold text-ink/55">{{ source === 'live' ? 'Live' : 'Demo' }}</span></div></section><section class="mx-auto max-w-2xl rounded-[22px] border border-line bg-white p-5 shadow-soft sm:p-8"><div class="flex items-center justify-between"><div><p class="text-xs font-extrabold text-ink/45">TUẦN NÀY</p><h2 class="mt-1 text-xl font-extrabold">Bảng XP</h2></div><span v-if="loading" class="text-xs text-ink/45">Đang cập nhật...</span></div><div class="mt-6 space-y-2"><div v-for="row in rows" :key="`${row.rank}-${row.name}`" :class="['flex items-center gap-3 rounded-2xl p-3', row.name === 'Bạn' ? 'bg-iris/10' : 'bg-paper']"><span class="grid h-9 w-9 place-items-center rounded-xl bg-white text-sm font-extrabold text-ink">{{ row.rank }}</span><span class="flex-1 text-sm font-bold">{{ row.name }}</span><span class="text-sm font-extrabold text-iris">{{ row.xp }} XP</span></div></div></section></div>
</template>
