<script setup lang="ts">
const { request } = useAppApi();
const loading = ref(false); const rows = ref<Array<{ rank: number; displayName: string; xp: number }>>([]); const notice = ref('');
onMounted(async () => { loading.value = true; try { rows.value = await request<Array<{ rank: number; displayName: string; xp: number }>>('/leaderboard/xp', { query: { limit: 10 } }); } catch { notice.value = 'Chưa tải được bảng XP. Hãy thử lại sau.'; } finally { loading.value = false; } });
</script>

<template>
  <div class="page-enter space-y-6"><section class="rounded-[26px] bg-[#FFF6DF] p-6 shadow-soft sm:p-9"><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-extrabold tracking-[0.18em] text-[#A87400]">LEADERBOARD</p><h1 class="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Tiến bộ có bạn đồng hành.</h1><p class="mt-3 max-w-xl text-sm leading-6 text-ink/60">XP là tín hiệu vui để giữ nhịp, không phải một cuộc đua phải thắng mỗi ngày.</p></div><span class="rounded-xl bg-white/70 px-3 py-2 text-xs font-bold text-ink/55">Live</span></div></section><p v-if="notice" class="rounded-xl bg-bean/20 p-3 text-xs font-bold text-[#8B6400]">{{ notice }}</p><section class="mx-auto max-w-2xl rounded-[22px] border border-line bg-white p-5 shadow-soft sm:p-8"><div class="flex items-center justify-between"><div><p class="text-xs font-extrabold text-ink/45">TOÀN BỘ THỜI GIAN</p><h2 class="mt-1 text-xl font-extrabold">Bảng XP</h2></div><span v-if="loading" class="text-xs text-ink/45">Đang cập nhật...</span></div><div v-if="rows.length" class="mt-6 space-y-2"><div v-for="row in rows" :key="`${row.rank}-${row.displayName}`" class="flex items-center gap-3 rounded-2xl bg-paper p-3"><span class="grid h-9 w-9 place-items-center rounded-xl bg-white text-sm font-extrabold text-ink">{{ row.rank }}</span><span class="flex-1 text-sm font-bold">{{ row.displayName }}</span><span class="text-sm font-extrabold text-iris">{{ row.xp }} XP</span></div></div><div v-else-if="!loading" class="mt-6 rounded-2xl bg-paper p-5 text-center text-xs leading-5 text-ink/55">Chưa có XP được ghi nhận. Hoàn thành một phiên học đầu tiên để tạo dấu mốc.</div></section></div>
</template>
