<script setup lang="ts">
type PublishedVideo = { id: string; title: string; payload: Record<string, unknown> };
type VideoLesson = { id: string; title: string; category: string; length: string; summary: string; tone: string; mediaUrl?: string; source: 'live' | 'fallback' };
const { request } = useAppApi();
const config = useRuntimeConfig();
const selected = ref(0); const notice = ref(''); const liveVideos = ref<VideoLesson[]>([]);
const fallbackVideos: VideoLesson[] = [{ id: 'fallback-linking', title: 'Nối âm trong câu hỏi ngắn', category: 'Listening', length: '08:24', summary: 'Nhận diện liên kết âm để không bị rơi mất từ khoá.', tone: 'bg-[#E8F7FF]', source: 'fallback' }, { id: 'fallback-grammar', title: '3 dấu hiệu nhận biết thì hiện tại hoàn thành', category: 'Grammar', length: '12:10', summary: 'Ghi nhớ tín hiệu thời gian và vị trí của trạng từ.', tone: 'bg-[#E7F7F1]', source: 'fallback' }, { id: 'fallback-vocabulary', title: 'Từ vựng văn phòng qua tình huống', category: 'Vocabulary', length: '06:48', summary: 'Học từ trong một tình huống thay vì danh sách rời rạc.', tone: 'bg-[#FFF6DF]', source: 'fallback' }];
const videos = computed(() => liveVideos.value.length ? liveVideos.value : fallbackVideos);
const activeVideo = computed(() => videos.value[selected.value] ?? videos.value[0]);
function secondsToLabel(value: unknown) { const seconds = typeof value === 'number' && Number.isFinite(value) ? value : 0; return seconds ? `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}` : 'Video ngắn'; }
function mediaUrl(value: unknown) { return typeof value === 'string' ? `${config.public.apiBase}/media/${value}/file` : undefined; }
async function loadVideos() { try { const content = await request<PublishedVideo[]>('/content', { query: { type: 'VIDEO' } }); liveVideos.value = content.map((item, index) => ({ id: item.id, title: item.title, category: typeof item.payload.category === 'string' ? item.payload.category : 'TOEIC', length: secondsToLabel(item.payload.durationSec), summary: typeof item.payload.summary === 'string' ? item.payload.summary : 'Video được publish từ kho nội dung.', tone: ['bg-[#E8F7FF]', 'bg-[#E7F7F1]', 'bg-[#FFF6DF]'][index % 3], mediaUrl: mediaUrl(item.payload.mediaAssetId), source: 'live' })); } catch { notice.value = 'Chưa tải được thư viện video; đang hiển thị danh sách mẫu.'; } }
function selectVideo(index: number) { selected.value = index; }
onMounted(loadVideos);
</script>

<template>
  <div class="page-enter space-y-6"><section class="rounded-[26px] bg-[#E7F7F1] p-6 shadow-soft sm:p-9"><p class="text-xs font-extrabold tracking-[0.18em] text-leaf">VIDEO LAB</p><h1 class="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Học qua những đoạn ngắn.</h1><p class="mt-3 max-w-xl text-sm leading-6 text-ink/60">Chọn một video, xem một ý chính, rồi quay lại bài tập để biến nó thành phản xạ.</p></section><p v-if="notice" class="rounded-xl bg-bean/20 p-3 text-xs font-bold text-[#8B6400]">{{ notice }}</p><div class="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section v-if="activeVideo" :class="['min-w-0 rounded-[22px] p-5 shadow-soft sm:p-8', activeVideo.tone]"><div class="min-h-64 overflow-hidden rounded-2xl bg-ink text-white"><video v-if="activeVideo.mediaUrl" :key="activeVideo.id" class="h-full min-h-64 w-full bg-ink object-contain" controls preload="metadata" :src="activeVideo.mediaUrl" /><div v-else class="flex min-h-64 flex-col items-center justify-center p-6 text-center"><span class="text-3xl" aria-hidden="true">▣</span><p class="mt-3 text-sm font-extrabold">Video chưa sẵn sàng</p><p class="mt-2 max-w-sm text-xs leading-5 text-white/65">Admin cần upload, cho phép phát công khai và gắn file video vào bài này trước khi có thể xem.</p></div></div><p class="mt-5 text-xs font-extrabold text-ink/45">{{ activeVideo.category }} · {{ activeVideo.length }} · {{ activeVideo.source === 'live' ? 'Đã publish' : 'Bản mẫu' }}</p><h2 class="mt-2 text-2xl font-extrabold tracking-[-0.04em]">{{ activeVideo.title }}</h2><p class="mt-3 max-w-2xl text-sm leading-6 text-ink/65">{{ activeVideo.summary }}</p></section><aside class="min-w-0 space-y-3"><button v-for="(video, index) in videos" :key="video.id" :class="['w-full rounded-2xl border p-4 text-left transition focus-ring', selected === index ? 'border-iris bg-white shadow-soft' : 'border-line bg-white hover:border-iris/40']" @click="selectVideo(index)"><span class="text-[11px] font-extrabold text-iris">{{ video.category }} · {{ video.length }}</span><span class="mt-2 block text-sm font-extrabold">{{ video.title }}</span></button></aside></div></div>
</template>
