#!/usr/bin/env bash
# Redeploy on this server: pull the latest code, rebuild the images, back up the
# database, apply migrations, restart API + web and wait until both are healthy.
#
#   ./deploy/deploy.sh                 redeploy origin/main
#   ./deploy/deploy.sh --seed          also create the admin + demo data (first deploy only:
#                                      re-running it resets the seeded accounts' passwords)
#   ./deploy/deploy.sh --no-pull       redeploy whatever is checked out (e.g. a rollback)
#   ./deploy/deploy.sh --branch <name> pull another branch
#
# The server needs only Docker (with the compose plugin), git and openssl. The first run
# writes deploy/.env with fresh secrets; keep that file, the data depends on it.
set -Eeuo pipefail

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$DEPLOY_DIR")"
ENV_FILE="$DEPLOY_DIR/.env"
BACKUP_DIR="$DEPLOY_DIR/backups"
KEEP_BACKUPS=10

branch=main pull=1 seed=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed) seed=1 ;;
    --no-pull) pull=0 ;;
    --branch) branch="${2:?--branch cần tên nhánh}"; shift ;;
    -h|--help) sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Tham số không hợp lệ: $1 (xem --help)" >&2; exit 2 ;;
  esac
  shift
done

step() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }
trap 'die "Lỗi ở dòng $LINENO: $BASH_COMMAND"' ERR
compose() { docker compose -f "$DEPLOY_DIR/docker-compose.yml" --env-file "$ENV_FILE" --profile tools "$@"; }
env_get() { grep -E "^$1=" "$ENV_FILE" | tail -n 1 | cut -d= -f2-; }

for cmd in docker git openssl; do
  command -v "$cmd" >/dev/null || die "Server chưa có $cmd."
done
docker compose version >/dev/null 2>&1 || die "Cần Docker Compose v2 (lệnh 'docker compose')."
docker info >/dev/null 2>&1 || die "Không kết nối được Docker daemon. Thêm user vào nhóm docker hoặc chạy bằng sudo."

if [[ ! -f "$ENV_FILE" ]]; then
  step "Lần deploy đầu: tạo deploy/.env"
  host="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  host="${host:-localhost}"
  if [[ -t 0 ]]; then
    read -rp "IP hoặc domain public của server [$host]: " answer
    host="${answer:-$host}"
  fi
  install -m 600 /dev/null "$ENV_FILE"
  cat >> "$ENV_FILE" <<EOF
# Generated by deploy.sh on $(date -u +%F). Do not regenerate: POSTGRES_PASSWORD is baked
# into the database volume and AI_ENCRYPTION_KEY decrypts the stored AI provider keys.

# Public URLs the browser uses. Behind a reverse proxy with a domain, set e.g.
# WEB_URL=https://toeic.example.com and API_URL=https://api.toeic.example.com
WEB_URL=http://$host:3011
API_URL=http://$host:3010
WEB_PORT=3011
API_PORT=3010
# Set to 127.0.0.1 once a reverse proxy on this host fronts the ports.
WEB_BIND=0.0.0.0
API_BIND=0.0.0.0

POSTGRES_PASSWORD=$(openssl rand -hex 24)
JWT_ACCESS_SECRET=$(openssl rand -hex 48)
AI_ENCRYPTION_KEY=$(openssl rand -hex 32)

# local | s3 | r2 — see backend/.env.example for the matching STORAGE_* keys.
STORAGE_PROVIDER=local
EOF
  echo "Đã tạo $ENV_FILE (quyền 600). Mở file này nếu cần đổi URL, port hoặc storage."
fi

cd "$REPO_DIR"
prev_commit="$(git rev-parse --short HEAD)"
if (( pull )); then
  step "Lấy code mới nhất từ origin/$branch"
  [[ -z "$(git status --porcelain --untracked-files=no)" ]] || die "Server có file đã sửa chưa commit. Commit hoặc 'git stash' rồi chạy lại."
  git fetch --prune origin "$branch"
  git checkout -q "$branch"
  git merge --ff-only -q "origin/$branch"
fi
new_commit="$(git rev-parse --short HEAD)"
echo "Commit: $prev_commit → $new_commit ($(git log -1 --format=%s))"

step "Build image"
compose build api web migrate

step "Khởi động Postgres + Redis"
compose up -d --wait postgres redis

step "Backup database"
mkdir -p "$BACKUP_DIR"
backup="$BACKUP_DIR/toeic-$(date +%Y%m%d-%H%M%S)-$prev_commit.sql.gz"
install -m 600 /dev/null "$backup"
compose exec -T postgres pg_dump -U toeic -d toeic --no-owner | gzip > "$backup"
echo "$backup ($(du -h "$backup" | cut -f1))"
ls -1t "$BACKUP_DIR"/toeic-*.sql.gz | tail -n +$((KEEP_BACKUPS + 1)) | while read -r old; do rm -f -- "$old"; done

step "Chạy migration"
compose run --rm migrate

if (( seed )); then
  step "Seed admin + dữ liệu demo"
  export SEED_ADMIN_EMAIL="${SEED_ADMIN_EMAIL:-admin@dautoeic.local}"
  export SEED_LEARNER_EMAIL="${SEED_LEARNER_EMAIL:-learner@dautoeic.local}"
  export SEED_ADMIN_PASSWORD="${SEED_ADMIN_PASSWORD:-$(openssl rand -base64 18)}"
  export SEED_LEARNER_PASSWORD="${SEED_LEARNER_PASSWORD:-$(openssl rand -base64 18)}"
  # Bare -e forwards the value from this shell, so passwords never show up in `ps`.
  compose run --rm -e SEED_ADMIN_EMAIL -e SEED_LEARNER_EMAIL -e SEED_ADMIN_PASSWORD -e SEED_LEARNER_PASSWORD migrate npm run seed
fi

step "Khởi động lại API + web"
if ! compose up -d --wait --remove-orphans api web; then
  compose logs --tail 80 api web || true
  die "API/web không lên được (log ở trên). Quay về bản cũ: git checkout $prev_commit && $0 --no-pull"
fi

docker image prune -f >/dev/null

step "Deploy xong"
web_url="$(env_get WEB_URL)"
api_url="$(env_get API_URL)"
echo "Commit:  $prev_commit → $new_commit"
echo "Web:     $web_url"
echo "API:     $api_url/api/v1   (Swagger: $api_url/docs)"
echo "Backup:  $backup"
if (( seed )); then
  echo
  echo "Tài khoản seed (chỉ in lần này, hãy lưu lại):"
  echo "  Admin:   $SEED_ADMIN_EMAIL / $SEED_ADMIN_PASSWORD"
  echo "  Learner: $SEED_LEARNER_EMAIL / $SEED_LEARNER_PASSWORD"
fi
