<script setup lang="ts">
const { request, accessToken } = useAppApi();
const draft = ref(''); const posts = ref([{ id: '1', name: 'tran ngoc', time: '8 ngày', content: 'cho mình hỏi kinh nghiệm muốn nghe tốt thì phải học như thế nào?', tags: ['Listening'], comments: 12 }, { id: '2', name: 'Nguyễn Lê Bích Chi', time: '5 ngày', content: 'nghe đoạn ngắn tầm 2-3p, chép đến khi nào không chép nổi nữa rồi mới xem transcript nhé.', tags: ['Dictation'], comments: 8 }]); const notice = ref('');
async function createPost() { if (!draft.value.trim()) return; const content = draft.value.trim(); if (accessToken.value) { try { await request('/community/posts', { method: 'POST', body: { type: 'QUESTION', content, tags: ['Learner'] } }); } catch { notice.value = 'Bài đã được giữ ở bản nháp trên màn hình này.'; } } posts.value.unshift({ id: String(Date.now()), name: 'Bạn', time: 'vừa xong', content, tags: ['Learner'], comments: 0 }); draft.value = ''; }
</script>

<template>
  <div class="page-enter space-y-6"><section class="rounded-[26px] bg-[#E9E9FF] p-6 shadow-soft sm:p-9"><p class="text-xs font-extrabold tracking-[0.18em] text-iris">CỘNG ĐỒNG</p><h1 class="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Học cùng nhau vui hơn.</h1><p class="mt-3 max-w-xl text-sm leading-6 text-ink/60">Một câu hỏi tốt có thể rút ngắn cả tuần loay hoay. Chia sẻ cách học, xin feedback, và giữ nhịp cùng nhau.</p></section><div class="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section class="space-y-3"><div class="rounded-[22px] border border-line bg-white p-4 shadow-soft"><label class="text-xs font-extrabold text-ink/45" for="post-body">BẠN ĐANG HỌC GÌ?</label><textarea id="post-body" v-model="draft" rows="3" class="mt-3 w-full resize-none rounded-xl border border-line bg-paper px-3 py-3 text-sm outline-none focus:border-iris" placeholder="Đặt câu hỏi hoặc chia sẻ một mẹo nhỏ..." /><div class="mt-2 flex justify-end"><button class="rounded-xl bg-ink px-4 py-3 text-xs font-extrabold text-white transition hover:bg-iris disabled:opacity-40 focus-ring" :disabled="!draft.trim()" @click="createPost">Đăng bài</button></div><p v-if="notice" class="mt-2 text-xs font-bold text-[#A87400]">{{ notice }}</p></div><article v-for="post in posts" :key="post.id" class="rounded-[22px] border border-line bg-white p-5 shadow-soft"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-full bg-ink text-xs font-bold text-white">{{ post.name.slice(0, 1) }}</span><div><p class="text-sm font-extrabold">{{ post.name }}</p><p class="text-[11px] text-ink/40">{{ post.time }}</p></div></div><p class="mt-4 text-sm leading-7 text-ink/75">{{ post.content }}</p><div class="mt-4 flex flex-wrap items-center gap-2"><span v-for="tag in post.tags" :key="tag" class="rounded-lg bg-iris/10 px-2 py-1 text-[11px] font-bold text-iris"># {{ tag }}</span><button class="ml-auto rounded-lg px-2 py-1 text-xs font-bold text-ink/45 hover:bg-paper focus-ring">{{ post.comments }} bình luận</button></div></article></section><aside class="h-fit rounded-[22px] border border-line bg-white p-5 shadow-soft"><p class="text-xs font-extrabold text-ink/45">GÓC NHỎ CHO BẠN</p><h2 class="mt-2 text-xl font-extrabold tracking-[-0.04em]">Ba cách hỏi dễ nhận được câu trả lời</h2><ol class="mt-5 space-y-4 text-sm leading-6 text-ink/65"><li><span class="mr-2 font-extrabold text-iris">01</span>Nói rõ Part hoặc dạng câu hỏi.</li><li><span class="mr-2 font-extrabold text-iris">02</span>Chia sẻ điều bạn đã thử.</li><li><span class="mr-2 font-extrabold text-iris">03</span>Chọn đúng tag để mọi người tìm thấy.</li></ol></aside></div></div>
</template>
