<script setup lang="ts">
type User = { id: string; email: string; displayName: string; roles: string[]; plan: string };
type AuthResponse = { accessToken: string; refreshToken: string; user: User };
const { request, accessToken, refreshToken } = useAppApi();
const mode = ref<'login' | 'register'>('login'); const email = ref(''); const password = ref(''); const displayName = ref(''); const message = ref(''); const busy = ref(false); const user = ref<User | null>(null);

onMounted(async () => { if (!accessToken.value) return; try { user.value = await request<User>('/users/me'); } catch { accessToken.value = null; refreshToken.value = null; } });
async function submit() { if (!email.value || !password.value || (mode.value === 'register' && !displayName.value)) return; busy.value = true; message.value = ''; try { if (mode.value === 'register') { await request('/auth/register', { method: 'POST', body: { email: email.value, password: password.value, displayName: displayName.value } }); mode.value = 'login'; message.value = 'Tạo tài khoản thành công. Đăng nhập để bắt đầu.'; } else { const result = await request<AuthResponse>('/auth/login', { method: 'POST', body: { email: email.value, password: password.value } }); accessToken.value = result.accessToken; refreshToken.value = result.refreshToken; user.value = result.user; await navigateTo('/hub?tab=profile'); } } catch { message.value = mode.value === 'login' ? 'Email hoặc mật khẩu chưa đúng.' : 'Chưa tạo được tài khoản. Kiểm tra email và thử lại.'; } finally { busy.value = false; } }
async function logout() { if (refreshToken.value) await request('/auth/logout', { method: 'POST', body: { refreshToken: refreshToken.value } }).catch(() => undefined); accessToken.value = null; refreshToken.value = null; user.value = null; message.value = 'Bạn đã đăng xuất.'; }
async function updateName() { if (!user.value?.displayName.trim()) return; try { user.value = { ...user.value, ...(await request<Partial<User>>('/users/me', { method: 'PATCH', body: { displayName: user.value.displayName } })) }; message.value = 'Đã lưu tên hiển thị.'; } catch { message.value = 'Chưa lưu được thông tin.'; } }
</script>

<template>
  <div class="page-enter space-y-6"><section class="rounded-[26px] bg-mint p-6 shadow-soft sm:p-9"><p class="text-xs font-extrabold tracking-[0.18em] text-leaf">TÀI KHOẢN</p><h1 class="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Không gian của bạn.</h1><p class="mt-3 max-w-xl text-sm leading-6 text-ink/60">Đăng nhập để lưu tiến bộ, đồng bộ SRS, gửi bài viết và mở các tính năng dành cho bạn.</p></section><section v-if="!user" class="mx-auto max-w-md rounded-[22px] border border-line bg-white p-5 shadow-soft sm:p-8"><div class="flex rounded-xl bg-mint p-1"><button :class="['flex-1 rounded-lg px-3 py-2 text-xs focus-ring', mode === 'login' ? 'bg-white font-bold shadow-soft' : 'text-ink/50']" @click="mode = 'login'; message = ''">Đăng nhập</button><button :class="['flex-1 rounded-lg px-3 py-2 text-xs focus-ring', mode === 'register' ? 'bg-white font-bold shadow-soft' : 'text-ink/50']" @click="mode = 'register'; message = ''">Tạo tài khoản</button></div><div class="mt-6 space-y-3"><AppInput v-if="mode === 'register'" v-model="displayName" placeholder="Tên hiển thị" autocomplete="name" /><AppInput v-model="email" type="email" placeholder="Email" autocomplete="email" /><AppInput v-model="password" type="password" placeholder="Mật khẩu" autocomplete="current-password" /><AppButton class="w-full" :loading="busy" @click="submit">{{ busy ? 'Đang xử lý...' : mode === 'login' ? 'Đăng nhập' : 'Tạo tài khoản' }}</AppButton></div><p v-if="message" class="mt-4 text-xs font-bold text-ink/60">{{ message }}</p></section><section v-else class="mx-auto max-w-2xl rounded-[22px] border border-line bg-white p-5 shadow-soft sm:p-8"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-extrabold text-ink/45">ĐÃ ĐĂNG NHẬP</p><h2 class="mt-1 text-2xl font-extrabold">Xin chào, {{ user.displayName }}</h2><p class="mt-2 text-sm text-ink/55">{{ user.email }} · Gói {{ user.plan }}</p></div><button class="rounded-xl border border-line px-3 py-2 text-xs font-extrabold hover:bg-mint focus-ring" @click="logout">Đăng xuất</button></div><div class="mt-7 rounded-2xl bg-mint p-4"><label class="text-xs font-extrabold text-ink/45" for="display-name">TÊN HIỂN THỊ</label><div class="mt-2 flex flex-wrap gap-2"><AppInput id="display-name" v-model="user.displayName" class="min-w-0 flex-1" /><AppButton size="sm" @click="updateName">Lưu</AppButton></div></div><p v-if="message" class="mt-4 text-xs font-bold text-ink/60">{{ message }}</p></section></div>
</template>
