<script setup lang="ts">
const { request, accessToken } = useAppApi();
const selected = ref('PRO'); const message = ref(''); const submitting = ref(false);
const plans = [{ code: 'PRO', name: 'Pro', price: '1.999.000đ', note: 'Cho người muốn học đều', features: ['Toàn bộ lộ trình TOEIC', 'SRS nâng cao', 'Feedback writing'] }, { code: 'PREMIUM', name: 'Premium', price: '2.499.000đ', note: 'Cho mục tiêu cần tăng tốc', features: ['Mọi quyền lợi Pro', 'Mock test theo mục tiêu', 'Ưu tiên hỗ trợ'] }];
async function choose() { submitting.value = true; message.value = ''; try { if (!accessToken.value) message.value = 'Bạn có thể xem gói ngay bây giờ. Đăng nhập để tạo đơn thanh toán.'; else { await request('/billing/orders', { method: 'POST', body: { planCode: selected.value } }); message.value = 'Đã tạo yêu cầu thanh toán. Bạn sẽ nhận hướng dẫn ở tài khoản.'; } } catch { message.value = 'Chưa tạo được đơn. Kiểm tra phiên đăng nhập rồi thử lại.'; } finally { submitting.value = false; } }
</script>

<template>
  <div class="page-enter space-y-6"><section class="rounded-[26px] bg-ink p-6 text-white shadow-float sm:p-9"><p class="text-xs font-extrabold tracking-[0.18em] text-bean">ĐẬU TOEIC PRO</p><h1 class="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Mở khoá nhịp học riêng.</h1><p class="mt-3 max-w-xl text-sm leading-6 text-white/65">Chọn một gói phù hợp với mục tiêu. Bạn luôn có thể bắt đầu bằng Free và nâng cấp khi cần.</p></section><div class="mx-auto grid max-w-4xl gap-4 md:grid-cols-2"><button v-for="plan in plans" :key="plan.code" :class="['rounded-[22px] border p-6 text-left shadow-soft transition hover:-translate-y-1 focus-ring', selected === plan.code ? 'border-iris bg-azure' : 'border-line bg-white']" @click="selected = plan.code"><span class="text-xs font-extrabold text-iris">{{ plan.name }}</span><span class="mt-3 block text-3xl font-extrabold tracking-[-0.05em]">{{ plan.price }}</span><span class="mt-2 block text-xs text-ink/50">{{ plan.note }}</span><span class="mt-6 block space-y-2 text-sm text-ink/70"><span v-for="feature in plan.features" :key="feature" class="flex items-center gap-2"><span class="text-grass"><AppIcon icon="solar:check-circle-bold" :size="17" /></span><span>{{ feature }}</span></span></span></button></div><div class="text-center"><button class="cta-grass px-5 py-3 text-xs font-extrabold disabled:opacity-40 focus-ring" :disabled="submitting" @click="choose">{{ submitting ? 'Đang tạo đơn...' : `Chọn gói ${selected}` }}</button><p v-if="message" class="mt-3 text-xs font-bold text-ink/60">{{ message }}</p></div></div>
</template>
