<script setup lang="ts">
import { countWords } from '~/utils/learning';
type WritingHistory = { id: string; part: number; wordCount: number; status: string; submittedAt: string | null; createdAt: string; grade: { overall: number | null; feedback: unknown; createdAt: string } | null };
const { request, accessToken } = useAppApi();
const body = ref(''); const submitting = ref(false); const status = ref(''); const result = ref<{ submissionId?: string; status?: string; creditsRemaining?: number } | null>(null); const history = ref<WritingHistory[]>([]); const historyLoading = ref(false);
const words = computed(() => countWords(body.value));
const dateLabel = (value: string | null) => value ? new Date(value).toLocaleDateString('vi-VN', { day: '2-digit', month: '2-digit' }) : 'Bản nháp';
async function loadHistory() { if (!accessToken.value) { history.value = []; return; } historyLoading.value = true; try { history.value = await request<WritingHistory[]>('/writing/submissions'); } catch { status.value ||= 'Chưa tải được lịch sử bài viết.'; } finally { historyLoading.value = false; } }
async function submit() { if (!body.value.trim() || submitting.value) return; if (!accessToken.value) { status.value = 'Đăng nhập để gửi bài và lưu feedback vào hồ sơ.'; return; } submitting.value = true; status.value = ''; try { result.value = await request('/writing/submissions', { method: 'POST', body: { part: 1, body: body.value } }); status.value = 'Bài viết đã được gửi. Đậu sẽ trả feedback theo tiêu chí TOEIC.'; body.value = ''; await loadHistory(); } catch { status.value = 'Chưa gửi được bài. Kiểm tra phiên đăng nhập hoặc lượt chấm rồi thử lại.'; } finally { submitting.value = false; } }
onMounted(loadHistory);
</script>

<template>
  <div class="page-enter space-y-6"><section class="rounded-[26px] bg-[#FFF6DF] p-6 shadow-soft sm:p-9"><p class="text-xs font-extrabold tracking-[0.18em] text-[#A87400]">WRITING LAB</p><h1 class="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Viết rõ ý hơn.</h1><p class="mt-3 max-w-xl text-sm leading-6 text-ink/60">Viết một đoạn ngắn theo prompt, rồi nhận góp ý về nội dung, ngữ pháp và từ vựng.</p></section><div class="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section class="min-w-0 rounded-[22px] border border-line bg-white p-5 shadow-soft sm:p-8"><div class="rounded-2xl bg-paper p-4"><p class="text-xs font-extrabold text-iris">PROMPT · PART 1</p><p class="mt-2 text-sm font-bold leading-6">Describe a useful change you would make to your daily study routine.</p></div><label class="mt-6 block text-xs font-bold" for="writing-body">Bài viết của bạn</label><textarea id="writing-body" v-model="body" rows="12" class="mt-2 w-full rounded-2xl border border-line bg-paper px-4 py-3 text-sm leading-7 outline-none focus:border-iris" placeholder="Bắt đầu viết ở đây..." /><div class="mt-3 flex flex-wrap items-center justify-between gap-3"><span class="text-xs text-ink/45">{{ words }} từ · Mục tiêu 80–120 từ</span><button class="rounded-xl bg-ink px-5 py-3 text-xs font-extrabold text-white transition hover:bg-iris disabled:opacity-40 focus-ring" :disabled="words === 0 || submitting" @click="submit">{{ submitting ? 'Đang gửi...' : 'Gửi chấm bài' }}</button></div><p v-if="status" class="mt-4 rounded-xl p-3 text-xs font-bold" :class="status.startsWith('Bài') ? 'bg-leaf/10 text-ink' : 'bg-bean/20 text-[#8B6400]'">{{ status }} <span v-if="result?.creditsRemaining !== undefined" class="font-medium text-ink/55">Còn {{ result.creditsRemaining }} lượt.</span></p></section><aside class="min-w-0 rounded-[22px] border border-line bg-white p-5 shadow-soft"><div class="flex items-end justify-between gap-3"><div><p class="text-xs font-extrabold text-ink/45">BÀI GẦN ĐÂY</p><h2 class="mt-1 text-xl font-extrabold">Lịch sử feedback</h2></div><span v-if="historyLoading" class="text-xs text-ink/45">Đang tải...</span></div><ol v-if="history.length" class="mt-5 space-y-3"><li v-for="item in history" :key="item.id" class="rounded-2xl bg-paper p-4"><div class="flex items-center justify-between gap-3"><p class="text-xs font-extrabold">Part {{ item.part }} · {{ item.wordCount }} từ</p><span :class="['rounded-lg px-2 py-1 text-[10px] font-extrabold', item.status === 'GRADED' ? 'bg-leaf/15 text-[#28896D]' : 'bg-iris/10 text-iris']">{{ item.status }}</span></div><p class="mt-2 text-xs text-ink/50">{{ dateLabel(item.submittedAt ?? item.createdAt) }} <span v-if="item.grade?.overall !== null && item.grade">· {{ item.grade.overall }}/10</span></p></li></ol><div v-else-if="!historyLoading" class="mt-5 rounded-2xl bg-paper p-4 text-xs leading-6 text-ink/55">Bài viết đã gửi sẽ xuất hiện ở đây cùng trạng thái chấm và feedback.</div></aside></div></div>
</template>
