<script setup lang="ts">
import { countWords } from '~/utils/learning';
const { request, accessToken } = useAppApi();
const body = ref(''); const submitting = ref(false); const status = ref(''); const result = ref<{ submissionId?: string; status?: string; creditsRemaining?: number } | null>(null);
const words = computed(() => countWords(body.value));
async function submit() { if (!body.value.trim() || submitting.value) return; submitting.value = true; status.value = ''; try { if (accessToken.value) result.value = await request('/writing/submissions', { method: 'POST', body: { part: 1, body: body.value } }); else result.value = { status: 'GRADING' }; status.value = 'Bài viết đã được gửi. Đậu sẽ trả feedback theo tiêu chí TOEIC.'; } catch { status.value = 'Chưa gửi được bài. Kiểm tra phiên đăng nhập rồi thử lại nhé.'; } finally { submitting.value = false; } }
</script>

<template>
  <div class="page-enter space-y-6"><section class="rounded-[26px] bg-[#FFF6DF] p-6 shadow-soft sm:p-9"><p class="text-xs font-extrabold tracking-[0.18em] text-[#A87400]">WRITING LAB</p><h1 class="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Viết rõ ý hơn.</h1><p class="mt-3 max-w-xl text-sm leading-6 text-ink/60">Viết một đoạn ngắn theo prompt, rồi nhận góp ý về nội dung, ngữ pháp và từ vựng.</p></section><section class="mx-auto max-w-3xl rounded-[22px] border border-line bg-white p-5 shadow-soft sm:p-8"><div class="rounded-2xl bg-paper p-4"><p class="text-xs font-extrabold text-iris">PROMPT · PART 1</p><p class="mt-2 text-sm font-bold leading-6">Describe a useful change you would make to your daily study routine.</p></div><label class="mt-6 block text-xs font-bold" for="writing-body">Bài viết của bạn</label><textarea id="writing-body" v-model="body" rows="12" class="mt-2 w-full rounded-2xl border border-line bg-paper px-4 py-3 text-sm leading-7 outline-none focus:border-iris" placeholder="Bắt đầu viết ở đây..." /><div class="mt-3 flex flex-wrap items-center justify-between gap-3"><span class="text-xs text-ink/45">{{ words }} từ · Mục tiêu 80–120 từ</span><button class="rounded-xl bg-ink px-5 py-3 text-xs font-extrabold text-white transition hover:bg-iris disabled:opacity-40 focus-ring" :disabled="words === 0 || submitting" @click="submit">{{ submitting ? 'Đang gửi...' : 'Gửi chấm bài' }}</button></div><p v-if="status" class="mt-4 rounded-xl bg-leaf/10 p-3 text-xs font-bold text-ink">{{ status }} <span v-if="result?.creditsRemaining !== undefined" class="font-medium text-ink/55">Còn {{ result.creditsRemaining }} lượt.</span></p></section></div>
</template>
